# <h1> CMSC 197 (Maching Learning) QUIZ 1 </h1>
<br> Unit 1 : Introduction to Numerical Computing Using Python </br>
<br> Submitted by: JOHN MARKTON M. OLARTE </br> 
<br> Student Number: 201904529 </br>
<br> Submitted to: Ma'am ARA ABIGAIL E. AMBITA </br>


In [1]:
import numpy as np

# PART 1

## <p style="color:#49be25"> items 1-3 <p>
1. Create 2 1D arrays, y_hat and y
2. Initialize y_hat with 20 linearly spaced numbers between -1 and 1
3. Initialize y with 20 linearly spaced numbers between 0 and 1

<p style="color:#3E72E3"> A: We can create the arrays using np.array(...) function, and since we are to initialize them with 20 linearly spaced numbers from a given (start_num, end_num) we can use np.linespace(...) function. </p>

In [2]:
# Initialize y_hat with 20 linearly spaced numbers between -1 and 1
y_hat = np.array(np.linspace(-1, 1, 20))

# Prints the y_hat array
print(f"y_hat array: {y_hat}")

y_hat array: [-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


In [3]:
# Initialize y with 20 linearly spaced numbers between 0 and 1
y = np.array(np.linspace(0, 1, 20))

# Prints the y array
print(f"y array: {y}")

y array: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## <p style="color:#49be25"> item 4 </p>
4. Compute for the shape and dimension of y_hat and y.

<p style="color:#3E72E3"> A: To compute for the shape of y_hat and y, we can use the shape attribute </p>

In [4]:
shape_y_hat = y_hat.shape

# Since y_hat is a 1D array, the shape will only have one element. Which is the number of elements in the array.
print(f"shape of y_hat: {shape_y_hat[0]}")


shape of y_hat: 20


In [5]:
y_shape = y.shape

# Since y is a 1D array, the shape will only have one element. Which is the number of elements in the array.
print(f"shape of y: {y_shape[0]}")

shape of y: 20


<p style="color:#3E72E3"> A: To compute for the dimension of y_hat and y, we can use the ndim attribute </p>

In [6]:
dim_y_hat = y_hat.ndim

# Since y_hat is a 1D array, the dimension will be 1.
print(f"dimension of y_hat: {dim_y_hat}")

dimension of y_hat: 1


In [7]:
dim_y = y.ndim

# Since y is a 1D array, the dimension will be 1.
print(f"dimension of y: {dim_y}")

dimension of y: 1


## <p style="color:#49be25"> items 5-6 </p>
5. Create individual functions for each of the loss functions with y and y_hat as parameters
6. Each function should return the loss value (L)

### <p style="color:#134b5f"> MEAN SQUARED ERROR (MSE) </p>



In [8]:
def MSE(y_hat, y):
    # Loss Value (L)
    L = np.mean((y_hat - y)**2)
    return L

# Prints the MSE Loss Value for y_hat and y.
print(f"Mean Squared Error Loss Value (L) : {MSE(y_hat, y)}")

Mean Squared Error Loss Value (L) : 0.3421052631578948


### <p style="color:#134b5f"> MEAN ABSOLUTE ERROR (MAE) </p>

In [9]:
def MAE(y_hat, y):
    # Loss Value (L)
    L = np.mean(np.absolute(y_hat - y))
    return L

# Prints the MAE Loss Value for y_hat and y.
print(f"Mean Absolute Error Loss Value (L) : {MAE(y_hat, y)}")

Mean Absolute Error Loss Value (L) : 0.4999999999999999


### <p style="color:#134b5f"> MEAN SQUARED LOGARITHMIC ERROR (MSLE) </p>

In [10]:
def MSLE(y_hat, y):
    # Loss Value (L)
    L = np.mean((np.log(y_hat + 1) - np.log(y + 1))**2)
    
    if L == np.inf:
        return "Error, values contains negative variables which don't exist in log."
    # If there is no error, return the loss value.
    return L

# Prints the MSLE Loss Value for y_hat and y.
print(f"Mean Squared Logarithmic Error Loss Value (L) : {MSLE(y_hat, y)}")

Mean Squared Logarithmic Error Loss Value (L) : Error, values contains negative variables which don't exist in log.


C:\Users\johnm\AppData\Local\Temp\ipykernel_15604\436804316.py:3: RuntimeWarning: divide by zero encountered in log
  L = np.mean((np.log(y_hat + 1) - np.log(y + 1))**2)


### <p style="color:#134b5f"> MEAN ABSOLUTE PERCENTAGE ERROR (MAPE) </p>

In [11]:
def MAPE(y_hat, y):
    # Loss Value (L)
    L = np.mean(np.absolute((y_hat - y)/y))*100
    
    if L == np.inf:
        return "Error, values contains zero, which resulted in zero division error."
    # If there is no error, return the loss value in percentage.
    return L

# Prints the MAPE Loss Value for y_hat and y.
print(f"Mean Absolute Percentage Error Loss Value (L) : {MAPE(y_hat, y)} {'%' if MAPE(y_hat, y) != 'Error, values contains zero, which resulted in zero division error.' else ''}")

Mean Absolute Percentage Error Loss Value (L) : Error, values contains zero, which resulted in zero division error. 


C:\Users\johnm\AppData\Local\Temp\ipykernel_15604\4277310195.py:3: RuntimeWarning: divide by zero encountered in divide
  L = np.mean(np.absolute((y_hat - y)/y))*100


# PART 2

## <p style="color:#49be25"> item 1 </p>
Create a 1D array M with values from 1 to 16 using the arange function.

In [12]:
# Using Arange (Array Range) we can create a 1D array from 1 to n (not including n)
M = np.arange(1, 17)
print(f"M array: {M}")

M array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


## <p style="color:#49be25"> item 2 </p>
Reshape M into 4x4 array and store it to N

In [13]:
# We can reshape an array using the reshape function.
N = M.reshape(4, 4)
print(f"N array (4x4): \n{N}")

N array (4x4): 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## <p style="color:#49be25"> item 3 </p>
Get the 2nd row of N

In [14]:
# The second row of N is at index [1, :]
print(f"2nd Row of Array [N]: {N[1, :]}")

2nd Row of Array [N]: [5 6 7 8]


## <p style="color:#49be25"> item 4 </p>

Get the minimum values for each column of N

In [15]:
# To get the minimum value of N, we can use the min function.
# axis is set to 0, since we want to find the minimum value for each column.
column_min = N.min(axis=0)

# Print the minimum value of each column.
for i in range(len(column_min)):
    print(f"Minimum value of column {i}: {column_min[i]}")

Minimum value of column 0: 1
Minimum value of column 1: 2
Minimum value of column 2: 3
Minimum value of column 3: 4


## <p style="color:#49be25"> item 5 </p>
Get the locations of the minimum values for each column of N

In [16]:
# Print out the location of the minimum value in each column.
for i in column_min:
    location = np.where(N == i)
    print(f"minimum value: {i} || location in arrray [N]: row{location[0]} column{location[1]}\n")

minimum value: 1 || location in arrray [N]: row[0] column[0]

minimum value: 2 || location in arrray [N]: row[0] column[1]

minimum value: 3 || location in arrray [N]: row[0] column[2]

minimum value: 4 || location in arrray [N]: row[0] column[3]



## <p style="color:#49be25"> item 6 </p>
Get the average of the whole matrix

In [17]:
# Use mean function to find the mean of the whole matrix (N).
# Note that the mean of Matrix M and N are just the same.
average_N = N.mean()
print(f"The average of the whole matrix [N] is {average_N}")

The average of the whole matrix [N] is 8.5


## <p style="color:#49be25"> item 7 </p>
Create a vector V with 4 elements, each element is 1

In [18]:
V = np.array([1, 1, 1, 1])
print(f"vector V: {V}")

vector V: [1 1 1 1]


## <p style="color:#49be25"> item 8 </p>

Take the dot product of N and V

In [19]:
dot_res = np.dot(N, V)
print(f"Dot Product of matrix [N] and vector [V]: {dot_res}")

Dot Product of matrix [N] and vector [V]: [10 26 42 58]
